<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.2" name="Slime" tilewidth="16" tileheight="16" tilecount="612" columns="34">
 <image source="../characters/slime.png" width="544" height="289"/>
 <tile id="0" type="slime"/>
 <tile id="1" type="slime"/>
 <tile id="2" type="slime"/>
 <tile id="3" type="slime"/>
 <tile id="4" type="slime"/>
 <tile id="5" type="slime"/>
 <tile id="6" type="slime"/>
 <tile id="7" type="slime"/>
 <tile id="8" type="slime"/>
 <tile id="9" type="slime"/>
 <tile id="10" type="slime"/>
 <tile id="11" type="slime"/>
 <tile id="12" type="slime"/>
 <tile id="13" type="slime"/>
 <tile id="14" type="slime"/>
 <tile id="15" type="slime"/>
 <tile id="16" type="slime"/>
 <tile id="17" type="slime"/>
 <tile id="18" type="slime"/>
 <tile id="19" type="slime"/>
 <tile id="20" type="slime"/>
 <tile id="21" type="slime"/>
 <tile id="22" type="slime"/>
 <tile id="23" type="slime"/>
 <tile id="24" type="slime"/>
 <tile id="25" type="slime"/>
 <tile id="26" type="slime"/>
 <tile id="27" type="slime"/>
 <tile id="28" type="slime"/>
 <tile id="29" type="slime"/>
 <tile id="30" type="slime"/>
 <tile id="31" type="slime"/>
 <tile id="32" type="slime"/>
 <tile id="33" type="slime"/>
 <tile id="34" type="slime"/>
 <tile id="35" type="slime"/>
 <tile id="36" type="slime"/>
 <tile id="37" type="slime"/>
 <tile id="38" type="slime"/>
 <tile id="39" type="slime"/>
 <tile id="40" type="slime"/>
 <tile id="41" type="slime"/>
 <tile id="42" type="slime"/>
 <tile id="43" type="slime"/>
 <tile id="44" type="slime"/>
 <tile id="45" type="slime"/>
 <tile id="46" type="slime"/>
 <tile id="47" type="slime"/>
 <tile id="48" type="slime"/>
 <tile id="49" type="slime"/>
 <tile id="50" type="slime"/>
 <tile id="51" type="slime"/>
 <tile id="52" type="slime"/>
 <tile id="53" type="slime"/>
 <tile id="54" type="slime"/>
 <tile id="55" type="slime"/>
 <tile id="56" type="slime"/>
 <tile id="57" type="slime"/>
 <tile id="58" type="slime"/>
 <tile id="59" type="slime"/>
 <tile id="60" type="slime"/>
 <tile id="61" type="slime"/>
 <tile id="62" type="slime"/>
 <tile id="63" type="slime"/>
 <tile id="64" type="slime"/>
 <tile id="65" type="slime"/>
 <tile id="66" type="slime"/>
 <tile id="67" type="slime"/>
 <tile id="68" type="slime">
  <animation>
   <frame tileid="68" duration="100"/>
   <frame tileid="69" duration="100"/>
   <frame tileid="70" duration="100"/>
   <frame tileid="71" duration="100"/>
   <frame tileid="72" duration="100"/>
  </animation>
 </tile>
 <tile id="69" type="slime"/>
 <tile id="70" type="slime"/>
 <tile id="71" type="slime"/>
 <tile id="72" type="slime"/>
 <tile id="73" type="slime"/>
 <tile id="74" type="slime"/>
 <tile id="75" type="slime"/>
 <tile id="76" type="slime"/>
 <tile id="77" type="slime"/>
 <tile id="78" type="slime"/>
 <tile id="79" type="slime"/>
 <tile id="80" type="slime"/>
 <tile id="81" type="slime"/>
 <tile id="82" type="slime"/>
 <tile id="83" type="slime"/>
 <tile id="84" type="slime"/>
 <tile id="85" type="slime"/>
 <tile id="86" type="slime"/>
 <tile id="87" type="slime"/>
 <tile id="88" type="slime"/>
 <tile id="89" type="slime"/>
 <tile id="90" type="slime"/>
 <tile id="91" type="slime"/>
 <tile id="92" type="slime"/>
 <tile id="93" type="slime"/>
 <tile id="94" type="slime"/>
 <tile id="95" type="slime"/>
 <tile id="96" type="slime"/>
 <tile id="97" type="slime"/>
 <tile id="98" type="slime"/>
 <tile id="99" type="slime"/>
 <tile id="100" type="slime"/>
 <tile id="101" type="slime"/>
 <tile id="102" type="slime"/>
 <tile id="103" type="slime"/>
 <tile id="104" type="slime"/>
 <tile id="105" type="slime"/>
 <tile id="106" type="slime"/>
 <tile id="107" type="slime"/>
 <tile id="108" type="slime"/>
 <tile id="109" type="slime"/>
 <tile id="110" type="slime"/>
 <tile id="111" type="slime"/>
 <tile id="112" type="slime"/>
 <tile id="113" type="slime"/>
 <tile id="114" type="slime"/>
 <tile id="115" type="slime"/>
 <tile id="116" type="slime"/>
 <tile id="117" type="slime"/>
 <tile id="118" type="slime"/>
 <tile id="119" type="slime"/>
 <tile id="120" type="slime"/>
 <tile id="121" type="slime"/>
 <tile id="122" type="slime"/>
 <tile id="123" type="slime"/>
 <tile id="124" type="slime"/>
 <tile id="125" type="slime"/>
 <tile id="126" type="slime"/>
 <tile id="127" type="slime"/>
 <tile id="128" type="slime"/>
 <tile id="129" type="slime"/>
 <tile id="130" type="slime"/>
 <tile id="131" type="slime"/>
 <tile id="132" type="slime"/>
 <tile id="133" type="slime"/>
 <tile id="134" type="slime"/>
 <tile id="135" type="slime"/>
 <tile id="136" type="slime"/>
 <tile id="137" type="slime"/>
 <tile id="138" type="slime"/>
 <tile id="139" type="slime"/>
 <tile id="140" type="slime"/>
 <tile id="141" type="slime"/>
 <tile id="142" type="slime"/>
 <tile id="143" type="slime"/>
 <tile id="144" type="slime"/>
 <tile id="145" type="slime"/>
 <tile id="146" type="slime"/>
 <tile id="147" type="slime"/>
 <tile id="148" type="slime"/>
 <tile id="149" type="slime"/>
 <tile id="150" type="slime"/>
 <tile id="151" type="slime"/>
 <tile id="152" type="slime"/>
 <tile id="153" type="slime"/>
 <tile id="154" type="slime"/>
 <tile id="155" type="slime"/>
 <tile id="156" type="slime"/>
 <tile id="157" type="slime"/>
 <tile id="158" type="slime"/>
 <tile id="159" type="slime"/>
 <tile id="160" type="slime"/>
 <tile id="161" type="slime"/>
 <tile id="162" type="slime"/>
 <tile id="163" type="slime"/>
 <tile id="164" type="slime"/>
 <tile id="165" type="slime"/>
 <tile id="166" type="slime"/>
 <tile id="167" type="slime"/>
 <tile id="168" type="slime"/>
 <tile id="169" type="slime"/>
 <tile id="170" type="slime"/>
 <tile id="171" type="slime"/>
 <tile id="172" type="slime"/>
 <tile id="173" type="slime"/>
 <tile id="174" type="slime"/>
 <tile id="175" type="slime"/>
 <tile id="176" type="slime"/>
 <tile id="177" type="slime"/>
 <tile id="178" type="slime"/>
 <tile id="179" type="slime"/>
 <tile id="180" type="slime"/>
 <tile id="181" type="slime"/>
 <tile id="182" type="slime"/>
 <tile id="183" type="slime"/>
 <tile id="184" type="slime"/>
 <tile id="185" type="slime"/>
 <tile id="186" type="slime"/>
 <tile id="187" type="slime"/>
 <tile id="188" type="slime"/>
 <tile id="189" type="slime"/>
 <tile id="190" type="slime"/>
 <tile id="191" type="slime"/>
 <tile id="192" type="slime"/>
 <tile id="193" type="slime"/>
 <tile id="194" type="slime"/>
 <tile id="195" type="slime"/>
 <tile id="196" type="slime"/>
 <tile id="197" type="slime"/>
 <tile id="198" type="slime"/>
 <tile id="199" type="slime"/>
 <tile id="200" type="slime"/>
 <tile id="201" type="slime"/>
 <tile id="202" type="slime"/>
 <tile id="203" type="slime"/>
 <tile id="204" type="slime"/>
 <tile id="205" type="slime"/>
 <tile id="206" type="slime"/>
 <tile id="207" type="slime"/>
 <tile id="208" type="slime"/>
 <tile id="209" type="slime"/>
 <tile id="210" type="slime"/>
 <tile id="211" type="slime"/>
 <tile id="212" type="slime"/>
 <tile id="213" type="slime"/>
 <tile id="214" type="slime"/>
 <tile id="215" type="slime"/>
 <tile id="216" type="slime"/>
 <tile id="217" type="slime"/>
 <tile id="218" type="slime"/>
 <tile id="219" type="slime"/>
 <tile id="220" type="slime"/>
 <tile id="221" type="slime"/>
 <tile id="222" type="slime"/>
 <tile id="223" type="slime"/>
 <tile id="224" type="slime"/>
 <tile id="225" type="slime"/>
 <tile id="226" type="slime"/>
 <tile id="227" type="slime"/>
 <tile id="228" type="slime"/>
 <tile id="229" type="slime"/>
 <tile id="230" type="slime"/>
 <tile id="231" type="slime"/>
 <tile id="232" type="slime"/>
 <tile id="233" type="slime"/>
 <tile id="234" type="slime"/>
 <tile id="235" type="slime"/>
 <tile id="236" type="slime"/>
 <tile id="237" type="slime"/>
 <tile id="238" type="slime"/>
 <tile id="239" type="slime"/>
 <tile id="240" type="slime"/>
 <tile id="241" type="slime"/>
 <tile id="242" type="slime"/>
 <tile id="243" type="slime"/>
 <tile id="244" type="slime"/>
 <tile id="245" type="slime"/>
 <tile id="246" type="slime"/>
 <tile id="247" type="slime"/>
 <tile id="248" type="slime"/>
 <tile id="249" type="slime"/>
 <tile id="250" type="slime"/>
 <tile id="251" type="slime"/>
 <tile id="252" type="slime"/>
 <tile id="253" type="slime"/>
 <tile id="254" type="slime"/>
 <tile id="255" type="slime"/>
 <tile id="256" type="slime"/>
 <tile id="257" type="slime"/>
 <tile id="258" type="slime"/>
 <tile id="259" type="slime"/>
 <tile id="260" type="slime"/>
 <tile id="261" type="slime"/>
 <tile id="262" type="slime"/>
 <tile id="263" type="slime"/>
 <tile id="264" type="slime"/>
 <tile id="265" type="slime"/>
 <tile id="266" type="slime"/>
 <tile id="267" type="slime"/>
 <tile id="268" type="slime"/>
 <tile id="269" type="slime"/>
 <tile id="270" type="slime"/>
 <tile id="271" type="slime"/>
 <tile id="272" type="slime"/>
 <tile id="273" type="slime"/>
 <tile id="274" type="slime"/>
 <tile id="275" type="slime"/>
 <tile id="276" type="slime"/>
 <tile id="277" type="slime"/>
 <tile id="278" type="slime"/>
 <tile id="279" type="slime"/>
 <tile id="280" type="slime"/>
 <tile id="281" type="slime"/>
 <tile id="282" type="slime"/>
 <tile id="283" type="slime"/>
 <tile id="284" type="slime"/>
 <tile id="285" type="slime"/>
 <tile id="286" type="slime"/>
 <tile id="287" type="slime"/>
 <tile id="288" type="slime"/>
 <tile id="289" type="slime"/>
 <tile id="290" type="slime"/>
 <tile id="291" type="slime"/>
 <tile id="292" type="slime"/>
 <tile id="293" type="slime"/>
 <tile id="294" type="slime"/>
 <tile id="295" type="slime"/>
 <tile id="296" type="slime"/>
 <tile id="297" type="slime"/>
 <tile id="298" type="slime"/>
 <tile id="299" type="slime"/>
 <tile id="300" type="slime"/>
 <tile id="301" type="slime"/>
 <tile id="302" type="slime"/>
 <tile id="303" type="slime"/>
 <tile id="304" type="slime"/>
 <tile id="305" type="slime"/>
 <tile id="306" type="slime"/>
 <tile id="307" type="slime"/>
 <tile id="308" type="slime"/>
 <tile id="309" type="slime"/>
 <tile id="310" type="slime"/>
 <tile id="311" type="slime"/>
 <tile id="312" type="slime"/>
 <tile id="313" type="slime"/>
 <tile id="314" type="slime"/>
 <tile id="315" type="slime"/>
 <tile id="316" type="slime"/>
 <tile id="317" type="slime"/>
 <tile id="318" type="slime"/>
 <tile id="319" type="slime"/>
 <tile id="320" type="slime"/>
 <tile id="321" type="slime"/>
 <tile id="322" type="slime"/>
 <tile id="323" type="slime"/>
 <tile id="324" type="slime"/>
 <tile id="325" type="slime"/>
 <tile id="326" type="slime"/>
 <tile id="327" type="slime"/>
 <tile id="328" type="slime"/>
 <tile id="329" type="slime"/>
 <tile id="330" type="slime"/>
 <tile id="331" type="slime"/>
 <tile id="332" type="slime"/>
 <tile id="333" type="slime"/>
 <tile id="334" type="slime"/>
 <tile id="335" type="slime"/>
 <tile id="336" type="slime"/>
 <tile id="337" type="slime"/>
 <tile id="338" type="slime"/>
 <tile id="339" type="slime"/>
 <tile id="340" type="slime"/>
 <tile id="341" type="slime"/>
 <tile id="342" type="slime"/>
 <tile id="343" type="slime"/>
 <tile id="344" type="slime"/>
 <tile id="345" type="slime"/>
 <tile id="346" type="slime"/>
 <tile id="347" type="slime"/>
 <tile id="348" type="slime"/>
 <tile id="349" type="slime"/>
 <tile id="350" type="slime"/>
 <tile id="351" type="slime"/>
 <tile id="352" type="slime"/>
 <tile id="353" type="slime"/>
 <tile id="354" type="slime"/>
 <tile id="355" type="slime"/>
 <tile id="356" type="slime"/>
 <tile id="357" type="slime"/>
 <tile id="358" type="slime"/>
 <tile id="359" type="slime"/>
 <tile id="360" type="slime"/>
 <tile id="361" type="slime"/>
 <tile id="362" type="slime"/>
 <tile id="363" type="slime"/>
 <tile id="364" type="slime"/>
 <tile id="365" type="slime"/>
 <tile id="366" type="slime"/>
 <tile id="367" type="slime"/>
 <tile id="368" type="slime"/>
 <tile id="369" type="slime"/>
 <tile id="370" type="slime"/>
 <tile id="371" type="slime"/>
 <tile id="372" type="slime"/>
 <tile id="373" type="slime"/>
 <tile id="374" type="slime"/>
 <tile id="375" type="slime"/>
 <tile id="376" type="slime"/>
 <tile id="377" type="slime"/>
 <tile id="378" type="slime"/>
 <tile id="379" type="slime"/>
 <tile id="380" type="slime"/>
 <tile id="381" type="slime"/>
 <tile id="382" type="slime"/>
 <tile id="383" type="slime"/>
 <tile id="384" type="slime"/>
 <tile id="385" type="slime"/>
 <tile id="386" type="slime"/>
 <tile id="387" type="slime"/>
 <tile id="388" type="slime"/>
 <tile id="389" type="slime"/>
 <tile id="390" type="slime"/>
 <tile id="391" type="slime"/>
 <tile id="392" type="slime"/>
 <tile id="393" type="slime"/>
 <tile id="394" type="slime"/>
 <tile id="395" type="slime"/>
 <tile id="396" type="slime"/>
 <tile id="397" type="slime"/>
 <tile id="398" type="slime"/>
 <tile id="399" type="slime"/>
 <tile id="400" type="slime"/>
 <tile id="401" type="slime"/>
 <tile id="402" type="slime"/>
 <tile id="403" type="slime"/>
 <tile id="404" type="slime"/>
 <tile id="405" type="slime"/>
 <tile id="406" type="slime"/>
 <tile id="407" type="slime"/>
 <tile id="408" type="slime"/>
 <tile id="409" type="slime"/>
 <tile id="410" type="slime"/>
 <tile id="411" type="slime"/>
 <tile id="412" type="slime"/>
 <tile id="413" type="slime"/>
 <tile id="414" type="slime"/>
 <tile id="415" type="slime"/>
 <tile id="416" type="slime"/>
 <tile id="417" type="slime"/>
 <tile id="418" type="slime"/>
 <tile id="419" type="slime"/>
 <tile id="420" type="slime"/>
 <tile id="421" type="slime"/>
 <tile id="422" type="slime"/>
 <tile id="423" type="slime"/>
 <tile id="424" type="slime"/>
 <tile id="425" type="slime"/>
 <tile id="426" type="slime"/>
 <tile id="427" type="slime"/>
 <tile id="428" type="slime"/>
 <tile id="429" type="slime"/>
 <tile id="430" type="slime"/>
 <tile id="431" type="slime"/>
 <tile id="432" type="slime"/>
 <tile id="433" type="slime"/>
 <tile id="434" type="slime"/>
 <tile id="435" type="slime"/>
 <tile id="436" type="slime"/>
 <tile id="437" type="slime"/>
 <tile id="438" type="slime"/>
 <tile id="439" type="slime"/>
 <tile id="440" type="slime"/>
 <tile id="441" type="slime"/>
 <tile id="442" type="slime"/>
 <tile id="443" type="slime"/>
 <tile id="444" type="slime"/>
 <tile id="445" type="slime"/>
 <tile id="446" type="slime"/>
 <tile id="447" type="slime"/>
 <tile id="448" type="slime"/>
 <tile id="449" type="slime"/>
 <tile id="450" type="slime"/>
 <tile id="451" type="slime"/>
 <tile id="452" type="slime"/>
 <tile id="453" type="slime"/>
 <tile id="454" type="slime"/>
 <tile id="455" type="slime"/>
 <tile id="456" type="slime"/>
 <tile id="457" type="slime"/>
 <tile id="458" type="slime"/>
 <tile id="459" type="slime"/>
 <tile id="460" type="slime"/>
 <tile id="461" type="slime"/>
 <tile id="462" type="slime"/>
 <tile id="463" type="slime"/>
 <tile id="464" type="slime"/>
 <tile id="465" type="slime"/>
 <tile id="466" type="slime"/>
 <tile id="467" type="slime"/>
 <tile id="468" type="slime"/>
 <tile id="469" type="slime"/>
 <tile id="470" type="slime"/>
 <tile id="471" type="slime"/>
 <tile id="472" type="slime"/>
 <tile id="473" type="slime"/>
 <tile id="474" type="slime"/>
 <tile id="475" type="slime"/>
 <tile id="476" type="slime"/>
 <tile id="477" type="slime"/>
 <tile id="478" type="slime"/>
 <tile id="479" type="slime"/>
 <tile id="480" type="slime"/>
 <tile id="481" type="slime"/>
 <tile id="482" type="slime"/>
 <tile id="483" type="slime"/>
 <tile id="484" type="slime"/>
 <tile id="485" type="slime"/>
 <tile id="486" type="slime"/>
 <tile id="487" type="slime"/>
 <tile id="488" type="slime"/>
 <tile id="489" type="slime"/>
 <tile id="490" type="slime"/>
 <tile id="491" type="slime"/>
 <tile id="492" type="slime"/>
 <tile id="493" type="slime"/>
 <tile id="494" type="slime"/>
 <tile id="495" type="slime"/>
 <tile id="496" type="slime"/>
 <tile id="497" type="slime"/>
 <tile id="498" type="slime"/>
 <tile id="499" type="slime"/>
 <tile id="500" type="slime"/>
 <tile id="501" type="slime"/>
 <tile id="502" type="slime"/>
 <tile id="503" type="slime"/>
 <tile id="504" type="slime"/>
 <tile id="505" type="slime"/>
 <tile id="506" type="slime"/>
 <tile id="507" type="slime"/>
 <tile id="508" type="slime"/>
 <tile id="509" type="slime"/>
 <tile id="510" type="slime"/>
 <tile id="511" type="slime"/>
 <tile id="512" type="slime"/>
 <tile id="513" type="slime"/>
 <tile id="514" type="slime"/>
 <tile id="515" type="slime"/>
 <tile id="516" type="slime"/>
 <tile id="517" type="slime"/>
 <tile id="518" type="slime"/>
 <tile id="519" type="slime"/>
 <tile id="520" type="slime"/>
 <tile id="521" type="slime"/>
 <tile id="522" type="slime"/>
 <tile id="523" type="slime"/>
 <tile id="524" type="slime"/>
 <tile id="525" type="slime"/>
 <tile id="526" type="slime"/>
 <tile id="527" type="slime"/>
 <tile id="528" type="slime"/>
 <tile id="529" type="slime"/>
 <tile id="530" type="slime"/>
 <tile id="531" type="slime"/>
 <tile id="532" type="slime"/>
 <tile id="533" type="slime"/>
 <tile id="534" type="slime"/>
 <tile id="535" type="slime"/>
 <tile id="536" type="slime"/>
 <tile id="537" type="slime"/>
 <tile id="538" type="slime"/>
 <tile id="539" type="slime"/>
 <tile id="540" type="slime"/>
 <tile id="541" type="slime"/>
 <tile id="542" type="slime"/>
 <tile id="543" type="slime"/>
 <tile id="544" type="slime"/>
 <tile id="545" type="slime"/>
 <tile id="546" type="slime"/>
 <tile id="547" type="slime"/>
 <tile id="548" type="slime"/>
 <tile id="549" type="slime"/>
 <tile id="550" type="slime"/>
 <tile id="551" type="slime"/>
 <tile id="552" type="slime"/>
 <tile id="553" type="slime"/>
 <tile id="554" type="slime"/>
 <tile id="555" type="slime"/>
 <tile id="556" type="slime"/>
 <tile id="557" type="slime"/>
 <tile id="558" type="slime"/>
 <tile id="559" type="slime"/>
 <tile id="560" type="slime"/>
 <tile id="561" type="slime"/>
 <tile id="562" type="slime"/>
 <tile id="563" type="slime"/>
 <tile id="564" type="slime"/>
 <tile id="565" type="slime"/>
 <tile id="566" type="slime"/>
 <tile id="567" type="slime"/>
 <tile id="568" type="slime"/>
 <tile id="569" type="slime"/>
 <tile id="570" type="slime"/>
 <tile id="571" type="slime"/>
 <tile id="572" type="slime"/>
 <tile id="573" type="slime"/>
 <tile id="574" type="slime"/>
 <tile id="575" type="slime"/>
 <tile id="576" type="slime"/>
 <tile id="577" type="slime"/>
 <tile id="578" type="slime"/>
 <tile id="579" type="slime"/>
 <tile id="580" type="slime"/>
 <tile id="581" type="slime"/>
 <tile id="582" type="slime"/>
 <tile id="583" type="slime"/>
 <tile id="584" type="slime"/>
 <tile id="585" type="slime"/>
 <tile id="586" type="slime"/>
 <tile id="587" type="slime"/>
 <tile id="588" type="slime"/>
 <tile id="589" type="slime"/>
 <tile id="590" type="slime"/>
 <tile id="591" type="slime"/>
 <tile id="592" type="slime"/>
 <tile id="593" type="slime"/>
 <tile id="594" type="slime"/>
 <tile id="595" type="slime"/>
 <tile id="596" type="slime"/>
 <tile id="597" type="slime"/>
 <tile id="598" type="slime"/>
 <tile id="599" type="slime"/>
 <tile id="600" type="slime"/>
 <tile id="601" type="slime"/>
 <tile id="602" type="slime"/>
 <tile id="603" type="slime"/>
 <tile id="604" type="slime"/>
 <tile id="605" type="slime"/>
 <tile id="606" type="slime"/>
 <tile id="607" type="slime"/>
 <tile id="608" type="slime"/>
 <tile id="609" type="slime"/>
 <tile id="610" type="slime"/>
 <tile id="611" type="slime"/>
</tileset>
